# Generated by Django 4.2 on 2023-08-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karer', '0002_alter_order_cargo_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name='The name of the fined driver')),
                ('driver_phone_number', models.CharField(max_length=16, verbose_name='The phone number of the fined driver')),
                ('driver_passport_or_id', models.CharField(choices=[('passport', 'Passport'), ('document_id', 'ID')], default='passport', max_length=11)),
                ('driver_passport_or_id_number', models.CharField(max_length=50, verbose_name="Driver's passport or ID number")),
                ('car_number', models.CharField(max_length=50, verbose_name='Fined driver car number')),
                ('car_photo', models.FileField(upload_to='tax_officers/violations/', verbose_name='Fined driver car photo')),
                ('location', models.CharField(max_length=100, verbose_name='The location of the fined driver')),
                ('cargo_date', models.DateField(auto_now=True, verbose_name='The time the cargo was picked up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='karer.cargotype', verbose_name='Cargo type')),
                ('tax_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name="Tax officer's profile")),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
            },
        ),
    ]
