# Generated by Django 4.2 on 2023-08-23 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tax_officer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karer_name', models.CharField(blank=True, max_length=100, verbose_name='Karer name')),
                ('driver_name', models.CharField(max_length=150, verbose_name='The name of the fined driver')),
                ('driver_phone_number', models.CharField(max_length=16, verbose_name='The phone number of the fined driver')),
                ('driver_passport_or_id', models.CharField(choices=[('passport', 'Passport'), ('document_id', 'ID')], default='passport', max_length=11)),
                ('driver_passport_or_id_number', models.CharField(max_length=50, verbose_name="Driver's passport or ID number")),
                ('car_number', models.CharField(max_length=50, verbose_name='Fined driver car number')),
                ('car_photo', models.FileField(upload_to='tax_officers/violations/', verbose_name='Fined driver car photo')),
                ('car_brand', models.CharField(blank=True, max_length=100, verbose_name='Car brand')),
                ('location', models.CharField(max_length=100, verbose_name='The location of the fined driver')),
                ('cargo_type', models.CharField(blank=True, max_length=100, verbose_name='Cargo type')),
                ('reason_violation', models.CharField(blank=True, max_length=100, verbose_name='Reason violation')),
                ('is_updated', models.BooleanField(default=False, verbose_name='Is updated')),
                ('cargo_date', models.DateTimeField(verbose_name='The time the cargo was picked up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_number', models.IntegerField(blank=True, default=tax_officer.models.create_new_ref_number, unique=True)),
                ('tax_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name="Tax officer's profile")),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
            },
        ),
    ]
