# Generated by Django 4.2 on 2023-08-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name="Tax officer's name, surname, patronymic")),
                ('passport_or_id_number', models.CharField(max_length=50, verbose_name='Passport or ID number')),
                ('passport_or_id_file', models.FileField(upload_to='tax_officers/profile/', verbose_name='Passport or ID file')),
                ('position', models.CharField(max_length=100, verbose_name='The position of tax officer')),
                ('working_region', models.CharField(max_length=50, verbose_name='Region of the tax officer')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Phone number of the tax officer')),
                ('created_At', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Tax officer profile',
                'verbose_name_plural': 'Tax officers profile',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name='The name of the fined driver')),
                ('driver_phone_number', models.CharField(max_length=16, verbose_name='The phone number of the fined driver')),
                ('driver_passport_or_id_number', models.CharField(max_length=50, verbose_name='The passport or ID number of the fined driver')),
                ('car_number', models.CharField(max_length=50, verbose_name='Fined driver car number')),
                ('car_photo', models.FileField(upload_to='tax_officers/violations/', verbose_name='Fined driver car photo')),
                ('location', models.CharField(max_length=100, verbose_name='The location of the fined driver')),
                ('cargo_type', models.CharField(max_length=100, verbose_name='Cargo type')),
                ('date', models.DateField(verbose_name='Date of violation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='tax_officer.profile', verbose_name="Tax officer's profile")),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
            },
        ),
    ]
