# Generated by Django 4.2 on 2023-08-27 14:48

from django.db import migrations, models
import tax_officer.models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='unique_number',
            field=models.IntegerField(blank=True, default=tax_officer.models.create_new_ref_number),
        ),
    ]
