# Generated by Django 4.2 on 2023-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='cargo_date',
            field=models.DateTimeField(auto_now=True, verbose_name='The time the cargo was picked up'),
        ),
    ]
