# Generated by Django 4.2 on 2023-08-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
