# Generated by Django 4.2 on 2023-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0002_alter_violation_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='stir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stir'),
        ),
        migrations.AddField(
            model_name='violation',
            name='who',
            field=models.CharField(blank=True, max_length=100, verbose_name='Who'),
        ),
    ]
