# Generated by Django 4.2 on 2023-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0002_alter_violation_cargo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='cargo_date',
            field=models.DateTimeField(verbose_name='The time the cargo was picked up'),
        ),
    ]
