# Generated by Django 4.2 on 2023-08-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0004_violation_reason_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='reason_violation',
            field=models.CharField(blank=True, choices=[('not_entered', "Ma'lumot kiritilmagan"), ('entered_incorrect', "Ma'lumot notog'ri kiritilgan")], max_length=17, verbose_name='Reason violation'),
        ),
    ]
