# Generated by Django 4.2 on 2023-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_officer', '0005_alter_violation_reason_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Car brand'),
        ),
        migrations.AddField(
            model_name='violation',
            name='karer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Karer name'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='reason_violation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reason violation'),
        ),
    ]
