# Generated by Django 4.2 on 2023-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Is phone verified'),
        ),
    ]
