# Generated by Django 4.2 on 2023-08-10 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Karer's name")),
                ('phone_number', models.CharField(max_length=16, verbose_name="Karer's phone number")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karer', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Karer',
                'verbose_name_plural': 'Karers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name="Driver's name")),
                ('driver_phone_number', models.CharField(max_length=16, verbose_name="Driver's phone number")),
                ('driver_passport_or_id_file', models.FileField(upload_to='orders/driver/', verbose_name="Driver's passport or ID file")),
                ('driver_passport_or_id_number', models.CharField(max_length=50, verbose_name="Driver's passport or ID number")),
                ('car_number', models.CharField(max_length=50, verbose_name='Car number')),
                ('car_photo', models.FileField(upload_to='orders/car/', verbose_name='Car photo')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('cargo_type', models.CharField(max_length=150, verbose_name='Cargo type')),
                ('weight', models.CharField(max_length=150, verbose_name='Weight')),
                ('date', models.DateField(verbose_name='Date of order')),
                ('karer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karer.karer', verbose_name='Karer')),
            ],
        ),
    ]
