# Generated by Django 4.2 on 2023-08-12 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cargo Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name="Driver's name")),
                ('driver_phone_number', models.CharField(max_length=16, verbose_name="Driver's phone number")),
                ('driver_passport_or_id', models.CharField(choices=[('passport', 'Passport'), ('document_id', 'ID')], default='passport', max_length=11)),
                ('driver_passport_or_id_number', models.CharField(max_length=50, verbose_name="Driver's passport or ID number")),
                ('car_number', models.CharField(max_length=50, verbose_name='Car number')),
                ('car_photo', models.FileField(upload_to='orders/car/', verbose_name='Car photo')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('weight', models.CharField(max_length=150, verbose_name='Weight')),
                ('date', models.DateField(auto_now_add=True)),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='karer.cargotype')),
                ('karer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Karer')),
            ],
        ),
    ]
