# Generated by Django 4.2 on 2023-08-23 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import karer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cargo Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo unit',
                'verbose_name_plural': 'Cargo units',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name="Driver's name")),
                ('driver_phone_number', models.CharField(max_length=16, verbose_name="Driver's phone number")),
                ('driver_passport_or_id', models.CharField(choices=[('passport', 'Passport'), ('document_id', 'ID')], default='passport', max_length=11)),
                ('driver_passport_or_id_number', models.CharField(max_length=50, verbose_name="Driver's passport or ID number")),
                ('car_number', models.CharField(max_length=50, verbose_name='Car number')),
                ('car_photo', models.ImageField(upload_to='orders/car/', verbose_name='Car photo')),
                ('car_brand', models.CharField(blank=True, max_length=100, verbose_name='Car brand')),
                ('trailer', models.CharField(blank=True, max_length=100, verbose_name='Trailer')),
                ('trailer_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Trailer weight')),
                ('direction', models.CharField(blank=True, max_length=128, verbose_name='Direction')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('cargo_type', models.CharField(blank=True, max_length=100, verbose_name='Cargo type')),
                ('cargo_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cargo value')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Status Order')),
                ('violated', models.BooleanField(default=False, verbose_name='Violated')),
                ('date', models.DateField(auto_now_add=True)),
                ('unique_number', models.IntegerField(blank=True, default=karer.models.create_new_ref_number, unique=True)),
                ('cargo_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karer.cargounit')),
                ('karer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Karer')),
            ],
        ),
    ]
