# Generated by Django 4.2 on 2023-08-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karer.cargotype'),
        ),
    ]
