# Generated by Django 4.2 on 2023-08-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0003_alter_order_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stir'),
        ),
        migrations.AddField(
            model_name='order',
            name='who',
            field=models.CharField(blank=True, max_length=100, verbose_name='Who'),
        ),
    ]
