# Generated by Django 4.2 on 2023-08-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0003_cargounity_order_cargo_value_order_cargo_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CargoUnity',
            new_name='CargoUnit',
        ),
        migrations.AlterModelOptions(
            name='cargounit',
            options={'verbose_name': 'Cargo unity', 'verbose_name_plural': 'Cargo unities'},
        ),
    ]
