# Generated by Django 4.2 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0005_alter_cargounit_options_alter_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_photo',
            field=models.ImageField(upload_to='orders/car/', verbose_name='Car photo'),
        ),
    ]
