# Generated by Django 4.2 on 2023-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0006_alter_order_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Car brand'),
        ),
    ]
