# Generated by Django 4.2 on 2023-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0008_order_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AddField(
            model_name='order',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Trailer'),
        ),
        migrations.AddField(
            model_name='order',
            name='trailer_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Trailer weight'),
        ),
    ]
