# Generated by Django 4.2 on 2023-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0009_remove_order_weight_order_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status Order'),
        ),
    ]
