# Generated by Django 4.2 on 2023-08-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer', '0011_order_violated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo type'),
        ),
    ]
